Repository CircuitVerse/Interactive-Book, pull requests merged in 2020-05, with the labels that each got.

#276 Disqus included in sub pages
  docs/Combinational/N-Bit Parallel Adder & Subtractor.md
  docs/Combinational/full_adder.md
  docs/Combinational/full_sub.md
  docs/Combinational/half_adder.md
  docs/Combinational/half_sub.md
  docs/MSI/decoder.md
  docs/MSI/demux.md
  docs/MSI/encoder.md
  docs/MSI/mux.md
  docs/flipflop/d_flipflop.md
  docs/flipflop/jk_flipflop.md
  docs/flipflop/masterslave_jk_flipflop.md
  docs/flipflop/sr_flipflop.md
  docs/flipflop/t_flipflop.md
  docs/registers/pp.md
  docs/registers/ps.md
  docs/registers/sp.md
  docs/registers/ss.md
  index.md
Labels: enhancement

#283 updated docs and images of sequential.md
  assets/images/sequential_asynchronous_circuit.jpg
  assets/images/sequential_synchronous_circuit.jpg
  docs/sequential.md
Labels: documentation

#58 Reference links added
  docs/References.md
Labels: inactive

#282 Update Binary.md
  docs/binary.md
Labels: documentation

#298 Adding examples for binary operations
  docs/binary2.md
Labels: documentation

#301 Corrected grammatical errors of application.md
  docs/application.md
Labels: documentation

#119 Added interactive ALU circuit
  docs/alu.md
Labels: inactive
